### ISSUE TITLE
Cannot find module './AppLoading' from 'index.js'

### ISSUE THREAD

**Issue by xcarpentier** [expo/jest-exponent#2]
Hey @brentvatne,

As you ask me, I tag you on a new issue.

**jest stacktrace**
```
 FAIL  screens/User/__tests__/User.component.test.js
  ● Test suite failed to run

    Cannot find module './AppLoading' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:144:17)
      at Object.<anonymous> (node_modules/exponent/src/Components/index.js:1:298)
      at Object.<anonymous> (node_modules/exponent/src/Exponent.js:41:755)
```

Maybe because file is `/AppLoading.ios.js` and `/AppLoading.android.js`.

Do I need to mock it ?

**Comment by cyprusglobe** [comment]
@xcarpentier what does you test and AppLoading look like?

I'm having a hard time reproducing.

**Comment by xcarpentier** [comment]
**My test code**
```javascript
import 'react-native';
import React from 'react';
import renderer from 'react-test-renderer';
import { User } from '../User.component';

it('<User/> render correctly', () => {
  const tree = renderer.create(
    <User
      id={1}
      name="Xavier Carpentier"
      email="xcapetir@gmail.com"
    />
  ).toJSON();
  expect(tree).toMatchSnapshot();
});
```

But I found a solution : 
- import jest-exponent with new modules (for now before accept PR : github:xcarpentier/jest-exponent)
- import jest-resolve too
- import jest 18.0.0

**Comment by brentvatne** [comment]
This should be fixed on jest 19, I just tried this out and it worked as expected
